<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit567c6ff9c5279b8cc41559ff79a5e5b7
{
    public static $prefixLengthsPsr4 = array (
        'K' => 
        array (
            'Klein\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Klein\\' => 
        array (
            0 => __DIR__ . '/..' . '/klein/klein/src/Klein',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit567c6ff9c5279b8cc41559ff79a5e5b7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit567c6ff9c5279b8cc41559ff79a5e5b7::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
